version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "5055:8080"
    depends_on:
      - db
    environment:
      - DB_URI=Server=db,1433;Database=YourDatabaseName;User=sa;Password=YourStrong@Passw0rd;Trusted_Connection=False;MultipleActiveResultSets=True;TrustServerCertificate=True;

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
    volumes:
      - db_volume:/var/opt/mssql

volumes:
  db_volume:
